In [ ]:
### 작성해주세요
### tf를 통해 변수를 선언하고 for문을 이용하여 1부터 10까지 더해지는 코드를 작성해주세요
import tensorflow as tf

## 변수 선언
x= tf.Variable(0)

## for 문
for i in range(1, 10):
  x=x+i
  print("vlaue : {} ".format(x))

print("total sum : {}".format(x))

vlaue : 1
vlaue : 3
vlaue : 6
vlaue : 10
vlaue : 15
vlaue : 21
vlaue : 28
vlaue : 36
vlaue : 45
total sum : 45

In [ ]:
### 작성해주세요
### tf를 통해 변수를 선언하고 for문을 이용하여 1부터 10까지 더해지는 코드를 작성해주세요
import tensorflow as tf

## 변수 선언
x= tf.Variable(0)

## for 문
for i in range(1, 10):
  x = tf.add(x,i)
  print("vlaue : {} ".format(x))

print("total sum : {}".format(x))

vlaue : 1
vlaue : 3
vlaue : 6
vlaue : 10
vlaue : 15
vlaue : 21
vlaue : 28
vlaue : 36
vlaue : 45
total sum : 45