In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os
root = '/content/drive/My Drive/Lectures/LG_Electronics/python/day3/practice'
os.chdir(root)
!pwd

/content/drive/My Drive/Lectures/LG_Electronics/python/day3/practice

# 기술 통계 계산과 요약

## 요약 통계

|메서드|설명|
|---|---|
|head,tail|series나 dataframe의 몇 개 데이터만 보여줌|
|describe|series나 dataframe의 각 컬럼에 대한 요약 통계|
|count| na 값을 제외한 값의 개수를 반환|
|min, max| 최소값, 최대값|
|argmin, argmax|최소값, 최대값을 가진 색인의 위치(정수)를 반환|
|idxmin, idxmax|최소값, 최대값을 가진 색인의 값을 반환|
|sum|합|
|mean, median|평균, 중앙값|
|var, std|분산, 표준편차|

* pandas 객체의 기술 통계는 누락된 데이터를 배제하고 처리함.

In [ ]:
stock = pd.read_csv('stock_2020_01.csv', 
                    encoding = "euc-kr")

In [ ]:
stock.head()

                    Date    kospi  kosdaq  gold_fut_132030  Bond_273130
0  2020. 1. 2 오후 3:30:00  2175.17  674.02            10845       108215
1  2020. 1. 3 오후 3:30:00  2176.46  669.93            11000       108565
2  2020. 1. 6 오후 3:30:00  2155.07  655.31            11245       108745
3  2020. 1. 7 오후 3:30:00  2175.54  663.44            11180       108400
4  2020. 1. 8 오후 3:30:00  2151.31  640.94            11360       108270

In [ ]:
frame = pd.DataFrame([[10, 4, 'a'], [10, 2.5, 'b'], [np.nan, 10, 'a']], 
                     index=['i1', 'i2', 'i3'],
                      columns=['c1', 'c2', 'c3'])
frame

      c1    c2 c3
i1  10.0   4.0  a
i2  10.0   2.5  b
i3   NaN  10.0  a

In [ ]:
frame.describe()

         c1         c2
count   2.0   3.000000
mean   10.0   5.500000
std     0.0   3.968627
min    10.0   2.500000
25%    10.0   3.250000
50%    10.0   4.000000
75%    10.0   7.000000
max    10.0  10.000000

In [ ]:
frame.describe(include='object')

       c3
count   3
unique  2
top     a
freq    2

In [ ]:
frame.describe(include='all')

          c1         c2   c3
count    2.0   3.000000    3
unique   NaN        NaN    2
top      NaN        NaN    a
freq     NaN        NaN    2
mean    10.0   5.500000  NaN
std      0.0   3.968627  NaN
min     10.0   2.500000  NaN
25%     10.0   3.250000  NaN
50%     10.0   4.000000  NaN
75%     10.0   7.000000  NaN
max     10.0  10.000000  NaN

In [ ]:
frame.max()

c1    10
c2    10
c3     b
dtype: object

In [ ]:
frame.min(axis=1)

i1     4.0
i2     2.5
i3    10.0
dtype: float64

In [ ]:
frame.sum()

c1      20
c2    16.5
c3     aba
dtype: object

## unique, value_counts

|메서드|설명|
|---|---|
|unique|series에서 중복되는 값을 제외하고 유일값만 포함하는 배열을 반환.|
|value_conuts|series에서 유일값에 대한 색인과 도수를 계산|

In [ ]:
obj = pd.Series([2, 1, 3, 3, 1, 5, np.nan, 1, 2])
obj

0    2.0
1    1.0
2    3.0
3    3.0
4    1.0
5    5.0
6    NaN
7    1.0
8    2.0
dtype: float64

In [ ]:
obj.unique()

array([ 2.,  1.,  3.,  5., nan])

In [ ]:
obj.value_counts()

1.0    3
3.0    2
2.0    2
5.0    1
dtype: int64

In [ ]:
# normalize
obj.value_counts(normalize=True)

1.0    0.375
3.0    0.250
2.0    0.250
5.0    0.125
dtype: float64

In [ ]:
obj = pd.Series(list('abcabcaaa')+[None])
obj

0       a
1       b
2       c
3       a
4       b
5       c
6       a
7       a
8       a
9    None
dtype: object

In [ ]:
obj.unique()

array(['a', 'b', 'c', None], dtype=object)

In [ ]:
obj.value_counts()

a    5
c    2
b    2
dtype: int64

# 정렬

## Series 정렬

* Series.sort_index : index를 기준으로 정렬
* Series.sort_values: values를 기준으로 정렬

In [ ]:
obj = pd.Series([1,2,3,-1,-2], index=list('adebc'))

In [ ]:
obj

a    1
d    2
e    3
b   -1
c   -2
dtype: int64

In [ ]:
obj.sort_index()

a    1
b   -1
c   -2
d    2
e    3
dtype: int64

In [ ]:
obj.sort_index(ascending=False)

e    3
d    2
c   -2
b   -1
a    1
dtype: int64

In [ ]:
obj.sort_values()

c   -2
b   -1
a    1
d    2
e    3
dtype: int64

In [ ]:
obj = pd.Series([10, np.nan, 20, 0, np.nan])

In [ ]:
obj

0    10.0
1     NaN
2    20.0
3     0.0
4     NaN
dtype: float64

In [ ]:
obj.sort_values()

3     0.0
0    10.0
2    20.0
1     NaN
4     NaN
dtype: float64

In [ ]:
obj.sort_values(ascending=False)

2    20.0
0    10.0
3     0.0
1     NaN
4     NaN
dtype: float64

In [ ]:
obj.sort_values(na_position='first')

1     NaN
4     NaN
3     0.0
0    10.0
2    20.0
dtype: float64

## DataFrame 정렬

* DataFrame.sort_index: index를 기준으로 정렬
* DataFrame.sort_values: values를 기준으로 정렬

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape(3,3), index = list('acb'), columns = list('edf'))
frame

   e  d  f
a  0  1  2
c  3  4  5
b  6  7  8

In [ ]:
frame.sort_index()

   e  d  f
a  0  1  2
b  6  7  8
c  3  4  5

In [ ]:
frame.sort_index(axis=1)

   d  e  f
a  1  0  2
c  4  3  5
b  7  6  8

In [ ]:
frame = pd.DataFrame({'a': [5, 4, 10, 10, 8], 'b': [2, 0, 3, 1, 4] })
frame

    a  b
0   5  2
1   4  0
2  10  3
3  10  1
4   8  4

In [ ]:
frame

    a  b
0   5  2
1   4  0
2  10  3
3  10  1
4   8  4

In [ ]:
frame.sort_values(by='a', ascending = False)

    a  b
2  10  3
3  10  1
4   8  4
0   5  2
1   4  0

In [ ]:
frame.sort_values(by=['a', 'b'], ascending = [False, True])

    a  b
3  10  1
2  10  3
4   8  4
0   5  2
1   4  0

# 함수 적용과 매핑 apply, applymap, map

## Series

In [ ]:
series = pd.Series(np.arange(1, 4, 1)*100)
series

0    100
1    200
2    300
dtype: int64

In [ ]:
series.map('${}'.format)

0    $100
1    $200
2    $300
dtype: object

In [ ]:
series.map('{}달러'.format)

0    100달러
1    200달러
2    300달러
dtype: object

In [ ]:
# lambda
f = lambda x: np.add(x, 3)
series.map(f)

0    103
1    203
2    303
dtype: int64

In [ ]:
series.map({100:'C', 200:'B', 300:'A'})

0    C
1    B
2    A
dtype: object

In [ ]:
s = pd.Series([20, 21, 12], index=['London', 'New York', 'Helsinki'])
s

London      20
New York    21
Helsinki    12
dtype: int64

In [ ]:
s

London      20
New York    21
Helsinki    12
dtype: int64

In [ ]:
def sub_custom_value(x, val) :
    return x - val

In [ ]:
s.apply(sub_custom_value, args=(10,))

London      10
New York    11
Helsinki     2
dtype: int64

In [ ]:
def add_custom_values(x, **kwargs):
    for month in kwargs:
        x += kwargs[month]
    return x

In [ ]:
s.apply(add_custom_values, june=30 , july=20, august=25)

London      95
New York    96
Helsinki    87
dtype: int64

## DataFrame

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape(3, 4), dtype=int, columns = list('abcd'))
frame

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
frame

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
frame.apply(lambda x: x.max()-x.min())

a    8
b    8
c    8
d    8
dtype: int64

In [ ]:
frame.apply(lambda x: x.max()-x.min(), axis=1)

0    3
1    3
2    3
dtype: int64

In [ ]:
frame.applymap(lambda x: x**2)

    a   b    c    d
0   0   1    4    9
1  16  25   36   49
2  64  81  100  121

# 데이터 정제, 준비

## 데이터 삭제
- drop

In [ ]:
frame = pd.DataFrame(np.arange(16).reshape(4,4), 
                         columns = ['c1', 'c2', 'c3', 'c4'],
                         index = ['r1', 'r2', 'r3','r4'])
frame

    c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [ ]:
frame

    c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [ ]:
frame.drop('r1')

    c1  c2  c3  c4
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15

In [ ]:
frame.drop('c2', axis = 1)

    c1  c3  c4
r1   0   2   3
r2   4   6   7
r3   8  10  11
r4  12  14  15

In [ ]:
frame.drop(columns=['c3', 'c4'])

    c1  c2
r1   0   1
r2   4   5
r3   8   9
r4  12  13

In [ ]:
# inplace
frame.drop(['r2'], inplace=True)
frame

    c1  c2  c3  c4
r1   0   1   2   3
r3   8   9  10  11
r4  12  13  14  15

In [ ]:
# 할당 
frame = frame.drop(['r3'])
frame

    c1  c2  c3  c4
r1   0   1   2   3
r4  12  13  14  15

## 데이터 병합

### concat

In [ ]:
s1 = pd.Series([100, 200], index=['c', 'b'])
s2 = pd.Series([300, 300, 300], index=['c', 'd', 'e'])
s3 = pd.Series([500, 600], index=['f', 'g'])

In [ ]:
print(s1, s2, s3, sep='\n\n')

c    100
b    200
dtype: int64

c    300
d    300
e    300
dtype: int64

f    500
g    600
dtype: int64

In [ ]:
pd.concat([s1, s2, s3])

c    100
b    200
c    300
d    300
e    300
f    500
g    600
dtype: int64

In [ ]:
pd.concat([s1, s2], axis=1)

       0      1
c  100.0  300.0
b  200.0    NaN
d    NaN  300.0
e    NaN  300.0

In [ ]:
data1 = pd.DataFrame({'id': ['01', '02', '03', '04', '05', '06'], 'col1': np.random.randint(0, 50, 6), 'col2':np.random.randint(1000, 2000, 6)})
data2 = pd.DataFrame({'id': ['04', '05', '06', '07'], 'col1': np.random.randint(1000, 5000, 4)})

In [ ]:
pd.concat([data1, data2])

   id  col1    col2
0  01    43  1918.0
1  02    17  1103.0
2  03    31  1269.0
3  04    12  1991.0
4  05    19  1853.0
5  06     1  1127.0
0  04  3876     NaN
1  05  2076     NaN
2  06  1509     NaN
3  07  4533     NaN

In [ ]:
pd.concat([data1, data2], axis=1)

   id  col1  col2   id    col1
0  01    43  1918   04  3876.0
1  02    17  1103   05  2076.0
2  03    31  1269   06  1509.0
3  04    12  1991   07  4533.0
4  05    19  1853  NaN     NaN
5  06     1  1127  NaN     NaN

### merge

In [ ]:
data1 = pd.DataFrame({'id': ['01', '02', '03', '04', '05', '06'], 'col1': np.random.randint(0, 50, 6), 'col2':np.random.randint(1000, 2000, 6)})
data1

   id  col1  col2
0  01     5  1083
1  02    29  1548
2  03     6  1594
3  04    16  1763
4  05     7  1305
5  06    20  1070

In [ ]:
data2 = pd.DataFrame({'id': ['04', '05', '06', '07'], 'col1': np.random.randint(1000, 5000, 4)})
data2

   id  col1
0  04  4532
1  05  2599
2  06  4556
3  07  3547

In [ ]:
data1

   id  col1  col2
0  01     5  1083
1  02    29  1548
2  03     6  1594
3  04    16  1763
4  05     7  1305
5  06    20  1070

In [ ]:
data2

   id  col1
0  04  4532
1  05  2599
2  06  4556
3  07  3547

In [ ]:
#inner join
pd.merge(data1, data2, on='id')

   id  col1_x  col2  col1_y
0  04      16  1763    4532
1  05       7  1305    2599
2  06      20  1070    4556

In [ ]:
#left join
pd.merge(data1, data2, on='id', how='left')

   id  col1_x  col2  col1_y
0  01       5  1083     NaN
1  02      29  1548     NaN
2  03       6  1594     NaN
3  04      16  1763  4532.0
4  05       7  1305  2599.0
5  06      20  1070  4556.0

In [ ]:
# outer join
pd.merge(data1, data2, on='id', how='outer')

   id  col1_x    col2  col1_y
0  01     5.0  1083.0     NaN
1  02    29.0  1548.0     NaN
2  03     6.0  1594.0     NaN
3  04    16.0  1763.0  4532.0
4  05     7.0  1305.0  2599.0
5  06    20.0  1070.0  4556.0
6  07     NaN     NaN  3547.0

In [ ]:
# key 다를 경우
data1 = pd.DataFrame({'lkey': ['a', 'b', 'c', 'd'], 'value': [1, 2, 3, 5]})
data2 = pd.DataFrame({'rkey': ['d', 'e', 'a', 'c'], 'value': [5, 6, 7, 8]})

pd.merge(data1, data2, left_on='lkey', right_on='rkey')

  lkey  value_x rkey  value_y
0    a        1    a        7
1    c        3    c        8
2    d        5    d        5

## missing data 처리

|함수|설명|
|---|---|
|isnull|누락되거나 NA(not available) 값을 알려주는 불리언 값들이 저장된 객체를 반환|
|notnull|isnull과 반대되는 메서드|
|fillna|누락된 데이터에 값을 채우는 메서드. (특정한 값이나 ffill, bfill 같은 보간 메서드 적용)|
|dropna|누락된 데이터가 있는 축(로우, 컬럼)을 제외시키는 메서드|

In [ ]:
obj = pd.Series(['apple', 'mango', np.nan, None, 'peach'])

In [ ]:
obj

0    apple
1    mango
2      NaN
3     None
4    peach
dtype: object

In [ ]:
obj.isnull()

0    False
1    False
2     True
3     True
4    False
dtype: bool

In [ ]:
obj.notnull()

0     True
1     True
2    False
3    False
4     True
dtype: bool

In [ ]:
obj.dropna()

0    apple
1    mango
4    peach
dtype: object

In [ ]:
obj.fillna('-')

0    apple
1    mango
2        -
3        -
4    peach
dtype: object

In [ ]:
frame = pd.DataFrame([[np.nan, np.nan, np.nan, np.nan], [10, 5, 40, 6],
                      [5, 2, 30, 8], [20, np.nan, 20, 6], [15, 3, 10, np.nan]],
                     columns=['x1', 'x2', 'x3', 'y'])
frame

     x1   x2    x3    y
0   NaN  NaN   NaN  NaN
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  20.0  NaN  20.0  6.0
4  15.0  3.0  10.0  NaN

In [ ]:
frame.dropna()

     x1   x2    x3    y
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0

In [ ]:
# how
frame.dropna(how='all')

     x1   x2    x3    y
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  20.0  NaN  20.0  6.0
4  15.0  3.0  10.0  NaN

In [ ]:
frame['e'] = np.nan
frame

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

In [ ]:
# axis 
frame.dropna(axis=1, how='all')

     x1   x2    x3    y
0   NaN  NaN   NaN  NaN
1  10.0  5.0  40.0  6.0
2   5.0  2.0  30.0  8.0
3  20.0  NaN  20.0  6.0
4  15.0  3.0  10.0  NaN

In [ ]:
frame

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

In [ ]:
frame.fillna(0)

     x1   x2    x3    y    e
0   0.0  0.0   0.0  0.0  0.0
1  10.0  5.0  40.0  6.0  0.0
2   5.0  2.0  30.0  8.0  0.0
3  20.0  0.0  20.0  6.0  0.0
4  15.0  3.0  10.0  0.0  0.0

In [ ]:
frame.fillna({'x1': 10, 'y':0})

     x1   x2    x3    y   e
0  10.0  NaN   NaN  0.0 NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  0.0 NaN

In [ ]:
frame

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  NaN  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

In [ ]:
frame.fillna(method='bfill')

     x1   x2    x3    y   e
0  10.0  5.0  40.0  6.0 NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  3.0  20.0  6.0 NaN
4  15.0  3.0  10.0  NaN NaN

In [ ]:
frame.fillna(method='ffill')

     x1   x2    x3    y   e
0   NaN  NaN   NaN  NaN NaN
1  10.0  5.0  40.0  6.0 NaN
2   5.0  2.0  30.0  8.0 NaN
3  20.0  2.0  20.0  6.0 NaN
4  15.0  3.0  10.0  6.0 NaN

## 데이터 변형

### 중복제거

- duplicated() : 각 로우가 중복인지(True) 아닌지(False) 알려주는 불리언 series 반환 
- drop_duplicates(): duplicated 배열이 False인 dataframe 반환

In [ ]:
data = pd.DataFrame({'id':['0001', '0002', '0003', '0001'], 'name': ['a', 'b', 'c', 'a']})
data

     id name
0  0001    a
1  0002    b
2  0003    c
3  0001    a

In [ ]:
data.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
data.drop_duplicates()

     id name
0  0001    a
1  0002    b
2  0003    c

In [ ]:
data['phone'] = range(4)
data

     id name  phone
0  0001    a      0
1  0002    b      1
2  0003    c      2
3  0001    a      3

In [ ]:
data.drop_duplicates(subset=['id'], keep='last')

     id name  phone
1  0002    b      1
2  0003    c      2
3  0001    a      3